@echo off
cd /d D:\MYLG\App\mylg-landing\src\shared\ui
del avatar-stack.module.css
del AvatarStack.tsx
del blog-post-button.css
del BlogPostButton.tsx
del color-picker.css
del ColorPicker.tsx
del ConfirmModal.test.tsx
del ConfirmModal.tsx
del Counter.tsx
del cross-black.svg
del cross.svg
del EditableTextField.tsx
del footer.css
del Footer.tsx
del header.css
del Header.tsx
del InlineSVG.tsx
del intro-text.css
del introtext.json
del IntroText.tsx
del layout-pdf-buttons.module.css
del LayoutPdfButtons.tsx
del Map.tsx
del marker.css
del ModalWithStack.tsx
del motionTokens.ts
del NavBadge.tsx
del navigation-drawer.css
del Notification.module.css
del NotificationList.tsx
del notifications-drawer.css
del Notifications.css
del OptimisticImage.tsx
del PendingApprovalScreen.tsx
del preloader.css
del Preloader.tsx
del project-avatar.css
del ProjectAvatar.tsx
del PromptModal.tsx
del ReactionBar.tsx
del sentences.ts
del slide-show.css
del SlideShow.tsx
del SmoothScroll.tsx
del spinner-overlay.css
del spinner.css
del Spinner.tsx
del SpinnerOverlay.tsx
del SpinnerScreen.tsx
del squircle\*
del Squircle.stories.tsx
del Squircle.tsx
del SvgOverlayPortal.tsx
del ToastNotifications.tsx
del UserProfilePicture.tsx
del VerificationCodeModal.tsx
del WebSocketDiagnostic.tsx
del ErrorBoundary.tsx