cd D:\MYLG\App\mylg-landing\src\shared\ui
Remove-Item avatar-stack.module.css -ErrorAction SilentlyContinue
Remove-Item AvatarStack.tsx -ErrorAction SilentlyContinue
Remove-Item blog-post-button.css -ErrorAction SilentlyContinue
Remove-Item BlogPostButton.tsx -ErrorAction SilentlyContinue
Remove-Item color-picker.css -ErrorAction SilentlyContinue
Remove-Item ColorPicker.tsx -ErrorAction SilentlyContinue
Remove-Item ConfirmModal.test.tsx -ErrorAction SilentlyContinue
Remove-Item ConfirmModal.tsx -ErrorAction SilentlyContinue
Remove-Item Counter.tsx -ErrorAction SilentlyContinue
Remove-Item cross-black.svg -ErrorAction SilentlyContinue
Remove-Item cross.svg -ErrorAction SilentlyContinue
Remove-Item EditableTextField.tsx -ErrorAction SilentlyContinue
Remove-Item footer.css -ErrorAction SilentlyContinue
Remove-Item Footer.tsx -ErrorAction SilentlyContinue
Remove-Item header.css -ErrorAction SilentlyContinue
Remove-Item Header.tsx -ErrorAction SilentlyContinue
Remove-Item InlineSVG.tsx -ErrorAction SilentlyContinue
Remove-Item intro-text.css -ErrorAction SilentlyContinue
Remove-Item introtext.json -ErrorAction SilentlyContinue
Remove-Item IntroText.tsx -ErrorAction SilentlyContinue
Remove-Item layout-pdf-buttons.module.css -ErrorAction SilentlyContinue
Remove-Item LayoutPdfButtons.tsx -ErrorAction SilentlyContinue
Remove-Item Map.tsx -ErrorAction SilentlyContinue
Remove-Item marker.css -ErrorAction SilentlyContinue
Remove-Item ModalWithStack.tsx -ErrorAction SilentlyContinue
Remove-Item motionTokens.ts -ErrorAction SilentlyContinue
Remove-Item NavBadge.tsx -ErrorAction SilentlyContinue
Remove-Item navigation-drawer.css -ErrorAction SilentlyContinue
Remove-Item Notification.module.css -ErrorAction SilentlyContinue
Remove-Item NotificationList.tsx -ErrorAction SilentlyContinue
Remove-Item notifications-drawer.css -ErrorAction SilentlyContinue
Remove-Item Notifications.css -ErrorAction SilentlyContinue
Remove-Item OptimisticImage.tsx -ErrorAction SilentlyContinue
Remove-Item PendingApprovalScreen.tsx -ErrorAction SilentlyContinue
Remove-Item preloader.css -ErrorAction SilentlyContinue
Remove-Item Preloader.tsx -ErrorAction SilentlyContinue
Remove-Item project-avatar.css -ErrorAction SilentlyContinue
Remove-Item ProjectAvatar.tsx -ErrorAction SilentlyContinue
Remove-Item PromptModal.tsx -ErrorAction SilentlyContinue
Remove-Item ReactionBar.tsx -ErrorAction SilentlyContinue
Remove-Item sentences.ts -ErrorAction SilentlyContinue
Remove-Item slide-show.css -ErrorAction SilentlyContinue
Remove-Item SlideShow.tsx -ErrorAction SilentlyContinue
Remove-Item SmoothScroll.tsx -ErrorAction SilentlyContinue
Remove-Item spinner-overlay.css -ErrorAction SilentlyContinue
Remove-Item spinner.css -ErrorAction SilentlyContinue
Remove-Item Spinner.tsx -ErrorAction SilentlyContinue
Remove-Item SpinnerOverlay.tsx -ErrorAction SilentlyContinue
Remove-Item SpinnerScreen.tsx -ErrorAction SilentlyContinue
Remove-Item squircle -Recurse -ErrorAction SilentlyContinue
Remove-Item Squircle.stories.tsx -ErrorAction SilentlyContinue
Remove-Item Squircle.tsx -ErrorAction SilentlyContinue
Remove-Item SvgOverlayPortal.tsx -ErrorAction SilentlyContinue
Remove-Item ToastNotifications.tsx -ErrorAction SilentlyContinue
Remove-Item UserProfilePicture.tsx -ErrorAction SilentlyContinue
Remove-Item VerificationCodeModal.tsx -ErrorAction SilentlyContinue
Remove-Item WebSocketDiagnostic.tsx -ErrorAction SilentlyContinue
Remove-Item ErrorBoundary.tsx -ErrorAction SilentlyContinue